# Generated by Django 4.2.16 on 2024-09-20 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notenanalyse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 20, 9, 10, 29, 30591)),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='content',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user_subject',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 20, 9, 10, 29, 31137)),
        ),
    ]
